import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const wrangler = JSON.parse(await readFile(new URL('../wrangler.jsonc', import.meta.url), 'utf8').then(x=>x.replace(/^\s*\/\*.*?\*\//s,'')));
assert(wrangler.compatibility_date <= '2026-09-29', 'compatibility date must not be near/future for the previous deployment context');
assert.equal(wrangler.durable_objects.bindings[0].class_name, 'Lobby');
assert.equal(wrangler.exports.Lobby.storage, 'sqlite');
assert.equal(wrangler.send_email?.[0]?.name, 'EMAIL');
assert.equal(wrangler.send_email?.[0]?.destination_address, 'ptornsaso0@gmail.com');
const matching = await readFile(new URL('../src/matching.js', import.meta.url), 'utf8');
assert(matching.includes('<= 9_000'), 'profile image must fit WebSocket attachment budget');
const app = await readFile(new URL('../public/app.js', import.meta.url), 'utf8');
assert(app.includes('reactionSoundsToggle'));
assert(app.includes('playoutDelayHint'));
assert(app.includes('chat-ack'));
assert(app.includes('messageId'));
assert(app.includes('remoteTitle'));
assert(matching.includes('findWaitingPeer'));
assert(app.includes('event.ctrlKey && event.shiftKey && event.altKey'));
assert(app.includes("adminCombo.join('') === 'elvarx'"));
assert(app.includes('reportCategoryGrid'));
assert(app.includes('/api/favorites'));
assert(app.includes('/api/groups'));
assert(app.includes('/api/auth/register'));
assert(app.includes('state.authenticated'));
const worker = await readFile(new URL('../src/index.js', import.meta.url), 'utf8');
assert(worker.includes("'/auth/register'"));
assert(worker.includes("'/favorites'"));
assert(worker.includes("'/groups'"));
assert(worker.includes('reportedUsers'));
assert(worker.includes('ADMIN_TOKEN'));
const security = await readFile(new URL('../src/security.js', import.meta.url), 'utf8');
assert(security.includes('PBKDF2-SHA-256'));
assert(security.includes('deriveBits'));
console.log('project invariants: OK');
